name: publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: git config --global user.email "golubkov.p.d@gmail.com"
      - run: git config --global user.name "Paul Golubkov"
      - run: npm install -g npm-cli-login lerna
      - run: npm-cli-login -u ${{ secrets.NPM_USER }} -p ${{secrets.NPM_PASSWORD }} -s @react-reusable -e ${{ secrets.NPM_EMAIL }}
      - run: lerna bootstrap
      - run: lerna publish patch --yes
